### ISSUE TITLE
Show 2nd match of double Grand Final only when needed

### ISSUE THREAD

**Issue by Drarig29** [Drarig29/brackets-viewer.js#16]
Currently, if the grand final of a double elimination stage is a double final (with two rounds), the 2nd match is always shown.

It would be good to show it only if the Lower Bracket winner wins the first match (which resets the final).

![image](https://user-images.githubusercontent.com/9317502/93900219-6c287800-fcf5-11ea-9ad3-2a48b368f584.png)

**Comment by Drarig29** [comment]
I think it's easier to always have an empty - unused - match in the database when there is a double grand final. This way, we just don't have to show it but it exists.

Adding and removing this match accordingly (like Toornament) would be harder to setup.

**Comment by PaulEvans8669** [comment]
Can I work on this? Thanks.

**Comment by Drarig29** [comment]
Of course! You are all set.
