### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by enchantinggg4** [Drarig29/brackets-viewer.js#26]
Is there any planning for adding translation support, or at least simple label scheme instead of hardcoded labels(e.g. BYE, WB etc)

**Comment by enchantinggg4** [comment]
Also, I might start implementing library in react, so if I have something to show, I'll create separate issue

**Comment by Drarig29** [comment]
I tried to move most of the language-specific things in the `lang.ts` file with i18n in mind.

This is definitely on the todo list.

I will try to do that.

**Comment by Drarig29** [comment]
> Also, I might start implementing library in react, so if I have something to show, I'll create separate issue

Ok. I tried to do a full vanilla and lightweight project. What would you want to do in React? Using the viewer or recreating it with React?

**Comment by enchantinggg4** [comment]
I'm thinking of recreating it based on vanilla.

**Comment by Drarig29** [comment]
By the way, I'm not using the viewer in a project where the scores are updated in real-time. That's why I don't use React with it.

When someone wants to get the latest data, he needs to refresh the page, just like in Toornament or Challonge.

**Comment by enchantinggg4** [comment]
Hm, It works for me with "hard" repaint, when data changes I re-render it. works fine on small brackets, but I am expecting it to become pretty nasty with bigger brackets

**Comment by Drarig29** [comment]
Yeah you're right. This viewer project is mostly for my needs right now.

You can have your React fork if you want.

I may want to create a public hosted editor to create tournaments etc. But I don't have much time right now.

Maybe I'll use your React fork in the future 😉 (for this editor)

**Comment by enchantinggg4** [comment]
Sure, time will tell

**Comment by enchantinggg4** [comment]
ah, only now noticed there is an issue already. Closing

**Comment by Drarig29** [comment]
Oh yeah, forgot that.

Marking as duplicate of #13

**Comment by Drarig29** [comment]
@enchantinggg4 there you go, you now have i18n 😉 (cf. PR https://github.com/Drarig29/brackets-viewer.js/pull/30)

I will wait to resolve other issues to make a new release, if you don't mind.

**Comment by Drarig29** [comment]
You can use this CDN link for now: https://cdn.jsdelivr.net/gh/Drarig29/brackets-viewer.js@i18n/dist/brackets-viewer.min.js
