### ISSUE TITLE
Export types and interfaces

### ISSUE THREAD

**Issue by Drarig29** [Drarig29/brackets-viewer.js#27]
Same as https://github.com/Drarig29/brackets-manager.js/issues/53

**Comment by Drarig29** [comment]
Also export the `BracketsViewer` class so that it can be imported in React for example.

So that instead of doing:

```js
// eslint-disable-next-line no-undef
bracketsViewer.render({
    stages: data.stage,
    matches: data.match,
    matchGames: data.match_game,
    participants: data.participant,
});
```

You can do:

```js
import { BracketsViewer } from 'brackets-viewer';

const bracketsViewer = new BracketsViewer();

bracketsViewer.render({
    stages: data.stage,
    matches: data.match,
    matchGames: data.match_game,
    participants: data.participant,
});
```

**Comment by Drarig29** [comment]
Fixing this should fix #60

**Comment by Abdulakibu** [comment]
Hey! Do you know when this will be added?

**Comment by Drarig29** [comment]
I'm not sure, but I might do it this week-end if you need it.

**Comment by Abdulakibu** [comment]
I'm using the other way but it would be nice. No rush either way.

**Comment by Drarig29** [comment]
`BracketsViewer` is now exported from `src/index.ts`
