### ISSUE TITLE
Make all getters in lang.ts

### ISSUE THREAD

**Issue by Drarig29** [Drarig29/brackets-viewer.js#28]
If we manually change language at runtime, some elements are not refreshed:

- `abbreviations`
- `BYE`
- `headers`

Transform them into getters.

**Comment by MrFastDie** [comment]
Other than that I would prefere having the i18n functionality exportet - in my opinion a lang.ts should not hold any logic, because by its name this modules purpose is giving the right translation for a key and not transforming such.

**Comment by Drarig29** [comment]
I removed the elements which were not refreshed, because they didn't have to be here.

I will keep the rest of the logic though.
