### ISSUE TITLE
Can this library be run under angular?

### ISSUE THREAD

**Issue by YouNone** [Drarig29/brackets-viewer.js#41]
I installed three packages:
     "brackets-manager": "^ 1.2.7",
     "brackets-model": "^ 1.3.5",
     "brackets-viewer": "^ 1.3.1"
     
But after this operation I could not find a detailed example of the installation. I was able to run the example with db.json and index html file, but that's all.

Therefore, I wanted to know if it can be run under angular and if so, how?

**Comment by Drarig29** [comment]
Yes you can do it, but manually. It's a vanilla library.

You have an example using React [here](https://repl.it/@Drarig29/React-and-brackets-viewerjs), you can take inspiration from it.

Basically, you need to add the library in your index.html in the public folder.

Once loaded in this file, the library will add a global variable `bracketsViewer` that you can use directly in your Angular code.

**Comment by Drarig29** [comment]
Currently the manager can't be used in the browser, you need to use it with Node.js, in a back-end.

And serving modules from your node_modules is a bad practice, so you should import the viewer with `<script>` and `<style>` tags.

**Comment by YouNone** [comment]
Thanks for the quick answer, I wanted to clarify if it is possible to access the bracketsViewer variable in a specific component?
I need something like this:
   
      
      
            
     import { bracketsViewer } from "brackets-viewer"
     export class Component implements OnInit {
      async getData() {
		const data = await fetch(URL).then(res => res.json());
		bracketsViewer.render({
			stages: data.stage,
			matches: data.match,
			matchGames: data.match_game,
			participants: data.participant,
		});
	}

	ngOnInit() {
		this.getData();
	}
}


   
And how to display in component-tree.html?

**Comment by Drarig29** [comment]
You don't need to import `bracketsViewer` in your components.

Add this in your index.html :

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/brackets-viewer/dist/brackets-viewer.min.css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brackets-viewer/dist/brackets-viewer.min.js"></script>
```

The library will define a global variable in the window object. So if you prefer, you can access it with `window.bracketsViewer`.

**Comment by Drarig29** [comment]
After that, I think adding an empty target div in your component-tree.html will do the job:

```html
<div class="bracket-viewer"></div> 
```

**Comment by YouNone** [comment]
Thanks again for the quick answer, the tree is displayed.

**Comment by aydinduygu** [comment]
> Thanks again for the quick answer, the tree is displayed.

Hi, do you still have the code for angular? Can you show how did you call the lib in ts file, thanks in advance

**Comment by Drarig29** [comment]
cc. @YouNone

**Comment by aydinduygu** [comment]
Hi @Drarig29; I am trying to implement in angular project. Although i have a html element with class name 'brackets-viewer', I am getting this error: 
![image](https://user-images.githubusercontent.com/62114034/233783305-87744c77-4dac-4094-88bb-b82ceb36bfc6.png)

It says 'Root not found'. Can you please help me. Thanks in advance

**Comment by Drarig29** [comment]
Which version of the viewer do you use?

**Comment by aydinduygu** [comment]
![image](https://user-images.githubusercontent.com/62114034/233784524-8d68bbdd-ff13-46cc-9d87-51cd16e8accc.png)

Hi again, I just removed this 't' from the code in the lib and problem is fixed (I hope). I have no idea why this works :-). Thanks for your interest

**Comment by Drarig29** [comment]
Here, `t` is the name for `selector` in the minified code. The `selector` parameter is passed here:

https://github.com/Drarig29/brackets-viewer.js/blob/4c9c685c897d4e98dc44119cfbd91d6f90fe856d/src/main.ts#L85

So you might have a `selector` property passed in your `bracketsViewer.render()` call, just like here:

https://github.com/Drarig29/brackets-viewer.js/blob/4c9c685c897d4e98dc44119cfbd91d6f90fe856d/demo/with-api.html#L62
