### ISSUE TITLE
Nuxt Integration - import issue

### ISSUE THREAD

**Issue by Emmanuel97423** [Drarig29/brackets-viewer.js#60]
Hello! How to import brackets-viewer module in component ?

I do : 

```js
@import { bracketsViewer } from 'brackets-viewer'
@import bracketsViewer  from 'brackets-viewer'
```

But dependency not found... The brackets-viewers its ok in node_modules.

@Drarig29 @ozgurg @Pustur Can you help me ?

Best regard,

**Comment by Drarig29** [comment]
I don't know Nuxt, I might need to do something to enable someone to import it.

Try to Google "use a vanilla javascript library with nuxt", you could find something. I don't have much time right now, maybe I'll have a look tonight or in the week.

**Comment by Emmanuel97423** [comment]
> I don't know Nuxt, I might need to do something to enable someone to import it.
> 
> Try to Google "use a vanilla javascript library with nuxt", you could find something. I don't have much time right now, maybe I'll have a look tonight or in the week.

Thank you @Drarig29 i try and waiting your return .

**Comment by Emmanuel97423** [comment]
> I don't know Nuxt, I might need to do something to enable someone to import it.
> 
> Try to Google "use a vanilla javascript library with nuxt", you could find something. I don't have much time right now, maybe I'll have a look tonight or in the week.

Nuxt is framework for vue.js similar Next for React.

**Comment by Drarig29** [comment]
Ok, I investigated with Vue.js and Nuxt and here is what I ended up with:

I didn't want to bother with `require()` or `import` so I did the same as in my React demo: https://replit.com/@Drarig29/React-and-brackets-viewerjs

I will try later to solve the "not found in node_modules" issue.

So, I used the CDN and the library adds an instance of the viewer to the `window` object. You can access it like this: `window.bracketsViewer`.

If you don't want to include the library in the whole app but only in a page, you can use the `head()` property of the page (not in `nuxt.config.js`) to load the library and the style. I let you adapt the solution like you want.

```vue
<template>
  <div class="bracket-viewer"></div>
</template>

<script>
export default {
  data() {
    return {
      url: "https://raw.githubusercontent.com/Drarig29/brackets-viewer.js/master/demo/db.json",
    };
  },
  mounted() {
    this.render();
  },
  methods: {
    async render() {
      const data = await fetch(this.url).then((res) => res.json());

      window.bracketsViewer.render({
        stages: data.stage,
        matches: data.match,
        matchGames: data.match_game,
        participants: data.participant,
      });
    },
  },
  head() {
    return {
      script: [
        {
          vmid: "brackets-viewer",
          src: "https://cdn.jsdelivr.net/npm/brackets-viewer/dist/brackets-viewer.min.js",
        },
      ],
      link: [
        {
          rel: "stylesheet",
          href: "https://cdn.jsdelivr.net/npm/brackets-viewer/dist/brackets-viewer.min.css",
        },
      ],
    };
  },
};
</script>

<style>
</style>
```

**Comment by Emmanuel97423** [comment]
@Drarig29 Thank you for the response. I do like that but there an issue : 
Uncaught (in promise) Error: Root not found. You must have at least one root element.

**Comment by Emmanuel97423** [comment]
> @Drarig29 Thank you for the response. I do like that but there an issue :
> Uncaught (in promise) Error: Root not found. You must have at least one root element.

Its ok dude sorry my className was bad
