### ISSUE TITLE
Uneven number of participants

### ISSUE THREAD

**Issue by meskalinchik** [Drarig29/brackets-viewer.js#71]
Hello everyone! Here is bracket from toornament:

https://play.toornament.com/en_US/tournaments/4937113874654773248/stages/4937116239538454528/

Is there a way to enhance connectors, when you handle uneven number of participants like on this bracket?

Thanks!

**Comment by Drarig29** [comment]
I transferred this issue to the viewer project.

The manager and the viewer use basic logic to know what match the participants come from and where they'll go afterwards. Hence the lack of support for uneven number of participants.

And this viewer project uses basic CSS placement to position the matches, so I won't be able to make something like Toornament without using a canvas or SVG. The least you could do is hide matches when there is BYEs but there will still be a gap remaining.

**Comment by meskalinchik** [comment]
> I transferred this issue to the viewer project.
> 
> The manager and the viewer use basic logic to know what match the participants come from and where they'll go afterwards. Hence the lack of support for uneven number of participants.
> 
> And this viewer project uses basic CSS placement to position the matches, so I won't be able to make something like Toornament without using a canvas or SVG. The least you could do is hide matches when there is BYEs but there will still be a gap remaining.

Thanks for your respond. Actually i did that, i mean hide matches, but this is not what i want it should be. Gonna try with polyline and svg. Good luck with your project. It's actually really cool! I think this issue can be closed.

**Comment by Drarig29** [comment]
> > I transferred this issue to the viewer project.
> > 
> > The manager and the viewer use basic logic to know what match the participants come from and where they'll go afterwards. Hence the lack of support for uneven number of participants.
> > 
> > And this viewer project uses basic CSS placement to position the matches, so I won't be able to make something like Toornament without using a canvas or SVG. The least you could do is hide matches when there is BYEs but there will still be a gap remaining.
> 
> Thanks for your respond. Actually i did that, i mean hide matches, but this is not what i want it should be. Gonna try with polyline and svg. Good luck with your project. It's actually really cool! I think this issue can be closed.

You can still use the manager if you wanted to. Just make your own viewer. You can fork mine too if you want, I'll gladly reference it in this project's README.
