### ISSUE TITLE
How use round robin mode for 5 or 6 players ?

### ISSUE THREAD

**Issue by shooter01** [Drarig29/brackets-viewer.js#72]
Hello! Thank you for this awesome library! But I always need to provide 4,8...etc players to create a tournament
How to handle the situation with 5 or 6 players?

**Comment by Drarig29** [comment]
You need to take the next power of two (if you want 6, you need 8) and fill the gaps with BYEs.

A BYE is a `null` in the seeding.

So your seeding would be:

```js
[
  "Team 1", "Team 2", "Team 3", "Team 4",
  "Team 5", "Team 6", null, null,
]
```
