### ISSUE TITLE
[Angular] Property 'bracketsViewer' does not exist on type 'Window & typeof globalThis'

### ISSUE THREAD

**Issue by Arturlo99** [Drarig29/brackets-viewer.js#79]
I have followed all of your instructions given within https://github.com/Drarig29/brackets-viewer.js/issues/41.
But the problem is that I still can't refer to `window.bracketsViewer` inside the .ts file of my component.
I receive such error:

![image](https://user-images.githubusercontent.com/49612999/143619303-aed78637-83c5-4c8d-9977-e7d46734db05.png)

I have noticed that I am able to refer this property using DevTools's console of my Google Chrome browser: 
![image](https://user-images.githubusercontent.com/49612999/143619686-7856fe82-b86b-40d0-9639-e967e30c749f.png)

Are you able to help me with this problem? I would really like to get editable brackets like here: https://replit.com/@Drarig29/brackets-viewerjs.

**Comment by Drarig29** [comment]
Put this somewhere (for example, in your your `app.module.ts`):

```ts
declare global {
    interface Window {
        bracketsViewer?: any | undefined;
    }
}
```

**Comment by Arturlo99** [comment]
It helped me, thanks :)
